/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VoltageDropImport } from './routes/voltage-drop'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const VoltageDropRoute = VoltageDropImport.update({
  id: '/voltage-drop',
  path: '/voltage-drop',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/voltage-drop': {
      id: '/voltage-drop'
      path: '/voltage-drop'
      fullPath: '/voltage-drop'
      preLoaderRoute: typeof VoltageDropImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/voltage-drop': typeof VoltageDropRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/voltage-drop': typeof VoltageDropRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/voltage-drop': typeof VoltageDropRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/voltage-drop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/voltage-drop'
  id: '__root__' | '/' | '/voltage-drop'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VoltageDropRoute: typeof VoltageDropRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VoltageDropRoute: VoltageDropRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/voltage-drop"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/voltage-drop": {
      "filePath": "voltage-drop.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
